"""notification system added seen row

Revision ID: 92a8125509a3
Revises: c9d93bb1c918
Create Date: 2026-03-11 11:24:48.606851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a8125509a3'
down_revision: Union[str, Sequence[str], None] = 'c9d93bb1c918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_seen', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['send_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'is_seen')
    # ### end Alembic commands ###
