"""update

Revision ID: bf42c60070b5
Revises: 8dc5877a3f6f
Create Date: 2026-03-06 15:47:50.012584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42c60070b5'
down_revision: Union[str, Sequence[str], None] = '8dc5877a3f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('send_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'users', ['send_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'send_by')
    # ### end Alembic commands ###
